FROM node:7.4.0-wheezy

MAINTAINER cmwd <pwojtkowiak@gmail.com>

RUN mkdir -p /tmp/build
ADD . /tmp/build

RUN npm install -g yarn

WORKDIR /tmp/build/
RUN yarn --pure-lockfile && npm run build

CMD tar -czf - build/

