export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_TALK = 'CREATE_EVENT_TALK';
export const DESTROY_EVENT = 'DESTROY_EVENT';
export const DESTROY_EVENT_TALK = 'DESTROY_EVENT_TALK';
export const UPDATE_EVENT_DESCRIPTION = 'UPDATE_EVENT_DESCRIPTION';
export const UPDATE_EVENT_TALK = 'UPDATE_EVENT_TALK';
export const UPDATE_CONFERENCE_INFO = 'UPDATE_CONFERENCE_INFO';
