export const CREATE_EVENT = 'CREATE_EVENT';
export const DESTROY_EVENT = 'DESTROY_EVENT';
export const UPDATE_EVENT_DESCRIPTION = 'UPDATE_EVENT_DESCRIPTION';
export const UPDATE_CONFERENCE_INFO = 'UPDATE_CONFERENCE_INFO';
