version: "2"
services:
  web:
    build: ./src/web/
    volumes:
      - ./src/web/:/usr/src/app/
    ports:
      - "8000:8000"
    links:
      - mongo
    environment:
      - NODE_DB_ADDRESS=mongodb://mongo:27017
      - NODE_PORT=8000
      - DEBUG=*
  data-sources:
    build: ./src/data-sources/
    volumes:
      - ./src/data-sources/:/usr/src/app/
    ports:
      - "8001:8001"
    links:
      - mongo
    environment:
      - NODE_DB_ADDRESS=mongodb://mongo:27017
      - NODE_PORT=8001
      - DEBUG=*
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
      image: tianon/true
      volumes:
        - /data/db
