version: "2"
services:
  api:
    build: ./src/api/
    restart: on-failure:20
    volumes:
      - ./src/api/:/var/www/api
      - /var/www/api/node_modules
    ports:
      - "8002"
    links:
      - mongo
    environment:
      - DB_URL=mongodb://mongo:27017
      - COLLECTORS_ADDRESS=http://collectors:8001
      - APP_PORT=8002
      - NODE_ENV=production
  editor:
    build: ./src/editor/
    volumes:
      - ./src/editor:/var/www/editor
      - /var/www/editor/node_modules
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017"
    volumes_from:
      - mongodata
  mongodata:
      image: tianon/true
      volumes:
        - /data/db
  nginx:
    build: ./src/nginx/
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/www/editor
    volumes_from:
      - editor
    links:
      - editor
      - api
