export const SELECT_CONFRENCES_PAGE = 'SELECT_CONFRENCES_PAGE';
export const SET_CONFERENCES_PAGE_DATA = 'SET_CONFERENCES_PAGE_DATA';
export const SET_CONFERENCES_LOADING_STATE = 'SET_CONFERENCES_LOADING_STATE';

export const SET_DETAILS_PAGE_DATA = 'SET_DETAILS_PAGE_DATA';
export const SET_DETAILS_LOADING_STATE = 'SET_DETAILS_LOADING_STATE';
