export const CONFERENCES_PAGE = {
  SET_PAGINATION_DATA: 'CONFERENCES_PAGE_SET_PAGINATION_DATA',
  SET_PAGINATION_INDEX: 'CONFERENCES_PAGE_SET_PAGINATION_INDEX',
};

export const DETAILS_PAGE = {
  SET_LOADING_STATE: 'DETAILS_PAGE_SET_LOADING_STATE',
  SET_VIDEOS_LOADING_STATE: 'DETAILS_PAGE_SET_VIDEOS_LOADING_STATE',
};

export const VIDEO = {
  SET_VIDEOS_DATA_FOR_CONFERENCE: 'VIDEO_SET_VIDEOS_DATA_FOR_CONFERENCE',
};

export const CONFERENCES = {
  PUT_CONFERENCE: 'CONFERENCES_PUT_CONFERENCE',
  SET_CONFERENCES: 'CONFERENCES_SET_CONFERENCES',
};
